# Site settings
author: Hunter Sides
title: My first portfolio project
header-img: img/home-bg.png
email: hunter.s.1337@gmail.com
copyright_name: Hunter Sides
description: > # this means to ignore newlines until "baseurl:"
  Portfolio project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ahhshethitman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
